# Site settings
title: Chegg Israel Office
email: yehuda@chegg.com
description: > # this means to ignore newlines until "baseurl:"
  We are on the mission to improve American students’ outcomes.
  We’re going to make the world better to study in by building
  products and services that help students save time,
  save money and get smarter!

# Build settings
markdown: kramdown
exclude: [config.rb]

# Site Globals
baseurl: http://www.chegg.co.il
url: http://www.chegg.co.il
